---
title: 'Financial Compensation between Federal States in Germany'
author: 'Workshop: Advanced R Programming'
date: 'Report Created: `r Sys.time()`'
output:
  html_document:
    toc: yes
    toc_float: yes
    code_folding: hide
    code_download: true
    theme: default
---

```{r setup, include=FALSE}

library(tidyverse)
library(glue)
library(plotly)

knitr::opts_chunk$set(echo = TRUE)
# knitr::opts_chunk$set(comment = NA)

laenderfinanz <- readRDS("Laenderfinanzausgleich.rds")
```


# Data

The following analyses are based on a dataset of `r nrow(laenderfinanz)` rows and `r ncol(laenderfinanz)` columns.


# Some Visualizations

## Arrow Chart, 2018 vs. 1995

1995 vs. 2018 is an interesting comparison:

* In 1995, the East German federal states were included for the first time.
* 2018 is the most recent time in this dataset.
* There were massive shifts in same states.

```{r arrows, echo = TRUE}

df <- laenderfinanz %>%
  select(-Typ) %>%
  pivot_wider(names_from = Jahr, values_from = Finanzausgleich)

ggplot(df, aes(x = `1995`, xend = `2018`,
               y = reorder(Bundesland, `2018`), yend = reorder(Bundesland, `2018`))) +
  geom_segment(size = 1.5, arrow = arrow(length = unit(0.3, "cm"))) +
  labs(x = "Financial Compensation, unit = 1 Million Euro",
       y = NULL,
       title = "Financial Compensation between Federal States\n1995 vs. 2018",
       caption = "Data: https://de.wikipedia.org/wiki/Länderfinanzausgleich#Finanzvolumen") +
  theme_bw() +
  theme(text = element_text(size = 12))


```

